{{- range $cronjob := $.Values.cronjobs }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjob.name }}
  namespace: {{ $.Values.environment }}
spec:
  schedule: "{{ $cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crons
            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - {{ $cronjob.command }}
          restartPolicy: OnFailure

{{- end }}