kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: development
  source:
    repoURL: https://github.com/egarcia2506/argocd-autopilot-testing.git
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc